### ISSUE TITLE
LAshow: Index out of bounds (Load_Read)LAshow: Index out of bounds (Load_Read)

### ISSUE THREAD

**Issue by orangeSi** [thegenemyers/DAMAPPER#1]
hi,Myers. I map an bacteria draft genome to the complete genome with DAMAPPER ,when use LAshow -a   to see the .las file,an error occured:
    LAshow: Index out of bounds (Load_Read)

thanks~

**Comment by thegenemyers** [comment]
I need a lot more information in order to be able to help you.
What is the error?  A crash or an error message.  What was the
exact sequence of command you ran, etc.

**Comment by orangeSi** [comment]
Query is bacteria draft genome,ref is the complete genome.
I generate xx.las with DAMAPPER.
when I ran "LAshow ref.db query.db xx.las -a ",an error( LAshow: Index out of bounds (Load_Read) )" occured.

**Comment by orangeSi** [comment]
my fault！I thought use  DAMAPPER but I used daligner!
now ,my command is this:
step1:    fasta2DAM untrimmed  991.untrimmed.reformat.fasta
             fasta2DAM uutig  uutigs.reformat.fasta
step2:    DBsplit -x1000 -s200 untrimmed

step3:    num=$(cat untrimmed.dam|grep blocks|awk '{print $3}')
              HPC.damapper -T2  -B4 -e.8 uutig untrimmed  1-$num >>run.job.sh 
step4：  sh run.jobs.sh 2>log

step5:     log file contains:
                   LAsort: Cannot open /tmp/uutig.0〮M_.las for 'r'
                   rm: cannot remove `/tmp/uutig.0\365\025\002.M_.las': No such file or directory
                   LAsort: Cannot open /tmp/uutig.پX틪.las for 'r'
                   rm: cannot remove `/tmp/uutig.\330\376X\3737.M*.las': No such file or directory
                   LAsort: Cannot open /tmp/uutig.پX틪.las for 'r'
                   rm: cannot remove`/tmp/uutig.\330\376X\3737.M*.las': No such file or directory
                   0 mapped segments
                   0 mapped segments
                   0 mapped segments

**Comment by orangeSi** [comment]
I should use "fasta2DB untrimmed 991.untrimmed.reformat.fasta" instead of "fasta2DAM untrimmed 991.untrimmed.reformat.fasta“！

**Comment by orangeSi** [comment]
Hi,Myers. I map pb subreads to genome with HPC.damapper,but still get the error when run "sh run.job.sh":
      0 mapped segments
LAsort: Cannot open /tmp/complete.PӮlas for 'r'
sh: .M_.las: command not found
LAcat: No #-sign in source name 'complete.Pӧ
sh: .M#.S: command not found
sh: : command not found
rm: cannot remove `/tmp/complete.P\325': No such file or directory
sh: .M_.las: command not found
LAcheck: Cannot open ./part.1.complete.las for 'r'

my command is :
step1:
fasta2DAM complete complete.fasta 
fasta2DB part subread.part.fasta

step2:
DBsplit -x100 -s2 part
DBsplit -x100 -s2 complete
num=$(cat part.db|grep blocks|awk '{print $3}')
echo num is $num
HPC.damapper -T2  -B4 -e.8 complete part   1-$num >>run.job.sh 

step3:
sh run.job.sh and get that error~

thanks~

**Comment by thegenemyers** [comment]
How big are complete and part?  Could you show me the result of

cat complete.db

and

cat part.db

Then show me the result of

cat run.job.sh

Thanks,  Gene

**Comment by orangeSi** [comment]
complete is one bacteria genome(size 4.5M), part is 69kb which is a part of total subreads .
**$cat complete.dam** 
files =         1
          1 complete complete
blocks =         1
size =    2000000 cutoff =       100 all = 0
         0         0
         1         1

**$cat part.db** 
files =         1
          7 subread.part m150924_183205_42266_c100886872550000001823193303261661_s1_p0
blocks =         1
size =    2000000 cutoff =       100 all = 0
         0         0
         7         5

**$cat run.job.sh** 
# Damapper jobs (1)
damapper -n1 complete part.1
# Check all .las files (optional but recommended)
LAcheck -vS part complete part.1.complete

**Comment by thegenemyers** [comment]
I found some bugs in the way damapper was handling /tmp files at the 
very end
which I believe is the problem you are seeing.  Could you please 
download the
updated version of the damapper module and see if I've fixed the problem?
    Thanks,
        Gene

**Comment by orangeSi** [comment]
updated version of the damapper module has fixed the problem~

thanks!
