### ISSUE TITLE
how to convert  .las  to .sam format?

### ISSUE THREAD

**Issue by orangeSi** [thegenemyers/DAMAPPER#3]
Hi, Gene~
          I get las file now,so want to convert las to sam file to do next analysis.

Thanks~
Si

**Comment by thegenemyers** [comment]
I don't have any software to do that.  There is a utility LAdump that 
will output
the contents of .las in an easy to read and intepret format.

However, I cc German Tischler in my group, I believe he does have a .las 
to .sam
converter that he can point you at.

```
-- Gene
```

**Comment by gt1** [comment]
In principle there is lastobam in lastools (see https://github.com/gt1/lastools). However this is not compatible with the current version of damapper, as it expect a certain order of the output which no longer holds for the latest version calling LAsort. Ways around that:
1. Use a previous version of damapper, e.g. https://github.com/thegenemyers/DAMAPPER/tree/79d2c2c9146799d425d46a975c84766f14e82078
2. Have an option in LAsort which allows sorting by the B read
3. Have a version of damapper which allows replacing of the LAsort call by a no-op. Just concatenating the output is fine for lastobam.

Best,
German

**Comment by gt1** [comment]
I have updated the lastools project (https://github.com/gt1/lastools). It now contains a program to generate the sort order necessary to produce BAM files from damapper's LAS files.

**Comment by orangeSi** [comment]
thanks~ @gt1 @thegenemyers
