### ISSUE TITLE
Memory allocation bug?

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DAMAPPER#6]
In map.c line 2595 (see https://github.com/thegenemyers/DAMAPPER/blob/master/map.c#L2595 ) there is 

part = Malloc(sizeof(Zones *)*COmax,"Allocating zones vector");

which I think should be

part = Malloc(sizeof(Zones)*COmax,"Allocating zones vector");

as part is of type Zones * .

Could you please check?

Thanks
German

**Comment by thegenemyers** [comment]
Yes, it is a bug.  The Realloc of part involves sizeof(Zones) so it 
would definitely induce a
segfault.  I have made the edit and pushed the change.
    -- Gene

**Comment by gt1** [comment]
Thank you.
German
