### ISSUE TITLE
How to convert reference.fasta to reference data base 

### ISSUE THREAD

**Issue by LeoChanW** [thegenemyers/DAMAPPER#8]
Hi!
I have a reference.fasta file. How to get ref:db|dam?

(damapper [-vbpCN] [-k<int(20)>] [-t<int>] [-M<int>] [-T<int(4)>]
                     [-e<double(.85)] [-s<int(100)>] [-n<double(1.)>]
                     [-m<track>]+ <ref:db|dam> <reads:db|dam> ...)

**Comment by thegenemyers** [comment]
You need to look at all the modules, there is a pipeline.  If you are 
looking for a single
program to call, then my system is not for you.

A DB is created from a .fasta file with fasta2DB.  See

    https://dazzlerblog.wordpress.com/2014/06/01/the-dazzler-db/
